Feature
sinework/Youtube-replica pull request #2
Opened 2020-08-12 17:12 UTC by coldatlas

Made a replica of a youtube video page, with a video player, suggested videos, description section, and a comment section.

2020-08-12 17:35 UTC, expjazz requested changes
## Welcome :+1: 

### Status: Changes Required :recycle: 

You did a very good job on this project :100: 

You made it responsive, the code is clean, well organized and I can see that you have a great attention to detail :clap: 

However, there are a few details (check the inline comments below) that will make the project even better. One thing that you did that you should not do again is to use styling inline in the HTML. You can check this article for a reference on why [https://speckyboy.com/good-bad-css-practices/](url)

Also, you can make the name of the pull request more meaningful, that represents more what you have achieved in this project.

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-08-12 17:35 UTC, expjazz commented on index.html
> +              style="cursor: pointer; margin-left: 10px; margin-right: 10px;"
- [ ] Kindly remove all the inline selectors since they are not a good practice.

2020-08-12 17:35 UTC, expjazz commented on index.html
> +          </div>
- [ ] I think the fonts-sizes could be closer to the original (channel name, number of views and comments). Make them smaller

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/90047359-2add8b00-dca8-11ea-839f-bae2568e4f15.png) |![image](https://user-images.githubusercontent.com/61479648/90047404-3cbf2e00-dca8-11ea-9dac-0fe9f2ac792b.png) |.

2020-08-12 17:35 UTC, expjazz commented on README.md
> +![screenshot](https://ibb.co/Yp0Gd05)
- [ ] The screenshot is not appearing

2020-08-13 01:41 UTC, bertil291utn commented
# **Status:** Approved ✅

## Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### And yes as my partner said, welcome to the program, you're going to love it

<h2 align="center">Ship it </h2>

<p align="center"><img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="100" /></p>

Please merge to master branch and move on with the next assignment.

You're doing  a great job keep going 💻 🚀 🔥

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

### OPTIONAL

-  Encourage the use of the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer

2020-08-13 07:38 UTC, merged